version: '3'

services:
  
  # `redislabs/redismod:latest` bundles together the latest stable releases of Redis and select Redis modules
  # see image dockerhub: https://hub.docker.com/r/redislabs/redismod
  search:
    image: redislabs/redismod:latest
    expose: 
      - 6379
    restart: unless-stopped
    volumes: 
      - redis_search_data:/data/

  # simple `redis:alpine3.16` -> used as a secondary redis instance for pubsub
  pubsub:
    image: redis:alpine3.16
    expose: 
      - 6379
    restart: unless-stopped

  # simple `redis:alpine3.16` -> used as a secondary redis instance for caching web API
  edge-cache:
    image: redis:alpine3.16
    expose: 
      - 6379
    restart: unless-stopped

  # simple `redis:alpine3.16` -> used as a secondary redis instance for persisting batch statuses
  batch-cache:
    image: redis:alpine3.16
    expose: 
      - 6379
    restart: unless-stopped
    volumes: 
      - redis_batch_cache_data:/data/
  
  # `redislabs/redisinsight:latest` -> used for viewing performance metrics
  insight:
    image: redislabs/redisinsight:latest
    ports: 
      - 8001:8001
    links:
      - search
      - pubsub
      - edge-cache
      - batch-cache

  # gcaas-edge is the HTTP service that is exposed to the user
  gcaas-edge:
    build: 
      context: ./../
      dockerfile: ./geocoder-svc/cmd/edge/Dockerfile
    expose: 
      - 2151
    ports: 
      - 2151:2151
    restart: unless-stopped
    command: /cmd/edge/edge \
        --host 0.0.0.0 \
        --port 2151 \
        --rpc-server-host gcaas-geocoder \
        --rpc-server-port 50051 \
        --batch-server-host gcaas-batch \
        --batch-server-port 50053 \
        --redis-host edge-cache \
        --redis-port 6379 \
        --redis-db 0 
    depends_on:
      - edge-cache
      - gcaas-geocoder
    links:
      - edge-cache
      - gcaas-geocoder

  # gcaas-geocoder is the grpc service that sits between the edge service and the redismod instance, 
  # allows for single and batch queries against redis search
  gcaas-geocoder:
    build: 
      context: ./../
      dockerfile: ./geocoder-svc/cmd/geocoder/Dockerfile
    expose: 
      - 50051
    ports: 
      - 50051:50051
    restart: unless-stopped
    command: /cmd/geocoder/geocoder \
        --host 0.0.0.0 \
        --port 50051 \
        --redis-host search \
        --redis-port 6379 \
        --redis-db 0
    depends_on:
      - search
    links:
      - search

  # gcaas-mgmt is an admin only service used for managing data in the search instance
  gcaas-mgmt:
    build: 
      context: ./../
      dockerfile: ./geocoder-svc/cmd/mgmt/Dockerfile
    expose: 
      - 50052
    ports: 
      - 50052:50052
    restart: unless-stopped
    command: /cmd/mgmt/mgmt \
        --host 0.0.0.0 \
        --port 50052 \
        --redis-host search \
        --redis-port 6379 \
        --redis-db 0
    depends_on:
      - search
    links:
      - search
    
  # gcaas-batch is a service used for managing batch requests - handles batch events and datasets
  # uploads
  gcaas-batch:
    build: 
      context: ./../
      dockerfile: ./geocoder-svc/cmd/batch/Dockerfile
    expose: 
      - 50053
    ports: 
      - 50053:50053
    restart: unless-stopped
    command: /cmd/batch/batch \
        --host 0.0.0.0 \
        --port 50053 \
        --redis-host batch-cache \
        --redis-port 6379 \
        --redis-db 0 \
        --pubsub-host pubsub \
        --pubsub-port 6379 \
        --pubsub-db 0
    depends_on:
      - pubsub
      - batch-cache
    links:
      - pubsub
      - batch-cache
    volumes:
      - ./tmp/:/tmp
    environment:
      - DO_SPACES_KEY=${DO_SPACES_KEY}
      - DO_SPACES_SECRET=${DO_SPACES_SECRET}
      - ENVIRONMENT=${ENVIRONMENT}

  # gcaas-worker is a service used for picking up batch jobs and streaming them to the geocoder
  gcaas-worker:
    build: 
      context: ./../
      dockerfile: ./geocoder-svc/cmd/worker/Dockerfile
    restart: unless-stopped
    command: /cmd/worker/worker \
        --pubsub-host pubsub \
        --pubsub-port 6379 \
        --pubsub-db 0 \
        --rpc-server-host gcaas-geocoder \
        --rpc-server-port 50051
    depends_on:
      - pubsub
    volumes:
      - ./tmp/:/tmp
    links:
      - pubsub
    environment:
      - DO_SPACES_KEY=${DO_SPACES_KEY}
      - DO_SPACES_SECRET=${DO_SPACES_SECRET}
      - ENVIRONMENT=${ENVIRONMENT}

volumes: 
  redis_search_data:
  redis_batch_cache_data:
  
networks:
  default: