// NOTE TO DEV:
// GENERATE WITH: protoc --go_out=. ./proto/geocoder.proto --go_opt=paths=source_relative --go-grpc_out=. --go-grpc_opt=paths=source_relative

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.28.1
// 	protoc        v3.21.5
// source: proto/geocoder.proto

package geocoder_proto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// Boro defines...
type Boro int32

const (
	Boro_UNDEFINED     Boro = 0
	Boro_MANHATTAN     Boro = 1
	Boro_BRONX         Boro = 2
	Boro_BROOKLYN      Boro = 3
	Boro_QUEENS        Boro = 4
	Boro_STATEN_ISLAND Boro = 5
	Boro_NASSAU        Boro = 6
	Boro_WESTCHESTER   Boro = 7
	Boro_NEW_JERSEY    Boro = 8
)

// Enum value maps for Boro.
var (
	Boro_name = map[int32]string{
		0: "UNDEFINED",
		1: "MANHATTAN",
		2: "BRONX",
		3: "BROOKLYN",
		4: "QUEENS",
		5: "STATEN_ISLAND",
		6: "NASSAU",
		7: "WESTCHESTER",
		8: "NEW_JERSEY",
	}
	Boro_value = map[string]int32{
		"UNDEFINED":     0,
		"MANHATTAN":     1,
		"BRONX":         2,
		"BROOKLYN":      3,
		"QUEENS":        4,
		"STATEN_ISLAND": 5,
		"NASSAU":        6,
		"WESTCHESTER":   7,
		"NEW_JERSEY":    8,
	}
)

func (x Boro) Enum() *Boro {
	p := new(Boro)
	*p = x
	return p
}

func (x Boro) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (Boro) Descriptor() protoreflect.EnumDescriptor {
	return file_proto_geocoder_proto_enumTypes[0].Descriptor()
}

func (Boro) Type() protoreflect.EnumType {
	return &file_proto_geocoder_proto_enumTypes[0]
}

func (x Boro) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use Boro.Descriptor instead.
func (Boro) EnumDescriptor() ([]byte, []int) {
	return file_proto_geocoder_proto_rawDescGZIP(), []int{0}
}

// Method defines...
type Method int32

const (
	Method_FWD_FUZZY   Method = 0
	Method_REV_NEAREST Method = 1
)

// Enum value maps for Method.
var (
	Method_name = map[int32]string{
		0: "FWD_FUZZY",
		1: "REV_NEAREST",
	}
	Method_value = map[string]int32{
		"FWD_FUZZY":   0,
		"REV_NEAREST": 1,
	}
)

func (x Method) Enum() *Method {
	p := new(Method)
	*p = x
	return p
}

func (x Method) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (Method) Descriptor() protoreflect.EnumDescriptor {
	return file_proto_geocoder_proto_enumTypes[1].Descriptor()
}

func (Method) Type() protoreflect.EnumType {
	return &file_proto_geocoder_proto_enumTypes[1]
}

func (x Method) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use Method.Descriptor instead.
func (Method) EnumDescriptor() ([]byte, []int) {
	return file_proto_geocoder_proto_rawDescGZIP(), []int{1}
}

// Point represents latitude-longitude pairs
// Latitudes in the range +/- 90 degrees and longitude in the range +/- 180 degrees.
type Point struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Latitude  float32 `protobuf:"fixed32,1,opt,name=latitude,proto3" json:"latitude,omitempty"`
	Longitude float32 `protobuf:"fixed32,2,opt,name=longitude,proto3" json:"longitude,omitempty"`
}

func (x *Point) Reset() {
	*x = Point{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_geocoder_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Point) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Point) ProtoMessage() {}

func (x *Point) ProtoReflect() protoreflect.Message {
	mi := &file_proto_geocoder_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Point.ProtoReflect.Descriptor instead.
func (*Point) Descriptor() ([]byte, []int) {
	return file_proto_geocoder_proto_rawDescGZIP(), []int{0}
}

func (x *Point) GetLatitude() float32 {
	if x != nil {
		return x.Latitude
	}
	return 0
}

func (x *Point) GetLongitude() float32 {
	if x != nil {
		return x.Longitude
	}
	return 0
}

// Address are
// Reference: https://data.cityofnewyork.us/api/views/g6pj-hd8k/files/375ad68c-4cea-45ff-aa9c-8307ae3ed7bb?download=true&filename=AddressPoint.pdf
type AddressData struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	HouseNum       string `protobuf:"bytes,1,opt,name=house_num,json=houseNum,proto3" json:"house_num,omitempty"` // Stores the address number. The field supports hyphenated and range based addresses (e.g. 457-459 7th Ave.)
	FullStreetName string `protobuf:"bytes,2,opt,name=full_street_name,json=fullStreetName,proto3" json:"full_street_name,omitempty"`
	Borocode       Boro   `protobuf:"varint,3,opt,name=borocode,proto3,enum=geocoder.Boro" json:"borocode,omitempty"`
	Zipcode        string `protobuf:"bytes,4,opt,name=zipcode,proto3" json:"zipcode,omitempty"`
}

func (x *AddressData) Reset() {
	*x = AddressData{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_geocoder_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *AddressData) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AddressData) ProtoMessage() {}

func (x *AddressData) ProtoReflect() protoreflect.Message {
	mi := &file_proto_geocoder_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AddressData.ProtoReflect.Descriptor instead.
func (*AddressData) Descriptor() ([]byte, []int) {
	return file_proto_geocoder_proto_rawDescGZIP(), []int{1}
}

func (x *AddressData) GetHouseNum() string {
	if x != nil {
		return x.HouseNum
	}
	return ""
}

func (x *AddressData) GetFullStreetName() string {
	if x != nil {
		return x.FullStreetName
	}
	return ""
}

func (x *AddressData) GetBorocode() Boro {
	if x != nil {
		return x.Borocode
	}
	return Boro_UNDEFINED
}

func (x *AddressData) GetZipcode() string {
	if x != nil {
		return x.Zipcode
	}
	return ""
}

type Address struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Location *Point       `protobuf:"bytes,1,opt,name=location,proto3" json:"location,omitempty"` //
	Data     *AddressData `protobuf:"bytes,2,opt,name=data,proto3" json:"data,omitempty"`         //
	Id       string       `protobuf:"bytes,3,opt,name=id,proto3" json:"id,omitempty"`
}

func (x *Address) Reset() {
	*x = Address{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_geocoder_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Address) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Address) ProtoMessage() {}

func (x *Address) ProtoReflect() protoreflect.Message {
	mi := &file_proto_geocoder_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Address.ProtoReflect.Descriptor instead.
func (*Address) Descriptor() ([]byte, []int) {
	return file_proto_geocoder_proto_rawDescGZIP(), []int{2}
}

func (x *Address) GetLocation() *Point {
	if x != nil {
		return x.Location
	}
	return nil
}

func (x *Address) GetData() *AddressData {
	if x != nil {
		return x.Data
	}
	return nil
}

func (x *Address) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

// IO
type IOResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Success             bool  `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	TotalObjectsWritten int32 `protobuf:"varint,2,opt,name=total_objects_written,json=totalObjectsWritten,proto3" json:"total_objects_written,omitempty"`
}

func (x *IOResponse) Reset() {
	*x = IOResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_geocoder_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *IOResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*IOResponse) ProtoMessage() {}

func (x *IOResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_geocoder_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use IOResponse.ProtoReflect.Descriptor instead.
func (*IOResponse) Descriptor() ([]byte, []int) {
	return file_proto_geocoder_proto_rawDescGZIP(), []int{3}
}

func (x *IOResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *IOResponse) GetTotalObjectsWritten() int32 {
	if x != nil {
		return x.TotalObjectsWritten
	}
	return 0
}

// Geocoding
type ScoredAddress struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Address           *Address `protobuf:"bytes,1,opt,name=address,proto3" json:"address,omitempty"`
	NormedConfidence  float32  `protobuf:"fixed32,2,opt,name=normed_confidence,json=normedConfidence,proto3" json:"normed_confidence,omitempty"`
	FullStreetAddress string   `protobuf:"bytes,4,opt,name=full_street_address,json=fullStreetAddress,proto3" json:"full_street_address,omitempty"`
}

func (x *ScoredAddress) Reset() {
	*x = ScoredAddress{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_geocoder_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ScoredAddress) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ScoredAddress) ProtoMessage() {}

func (x *ScoredAddress) ProtoReflect() protoreflect.Message {
	mi := &file_proto_geocoder_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ScoredAddress.ProtoReflect.Descriptor instead.
func (*ScoredAddress) Descriptor() ([]byte, []int) {
	return file_proto_geocoder_proto_rawDescGZIP(), []int{4}
}

func (x *ScoredAddress) GetAddress() *Address {
	if x != nil {
		return x.Address
	}
	return nil
}

func (x *ScoredAddress) GetNormedConfidence() float32 {
	if x != nil {
		return x.NormedConfidence
	}
	return 0
}

func (x *ScoredAddress) GetFullStreetAddress() string {
	if x != nil {
		return x.FullStreetAddress
	}
	return ""
}

// GeocodeRequest
type GeocodeRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// Types that are assignable to Query:
	//	*GeocodeRequest_AddressQuery
	//	*GeocodeRequest_PointQuery
	Query      isGeocodeRequest_Query `protobuf_oneof:"query"`
	MaxResults uint32                 `protobuf:"varint,3,opt,name=max_results,json=maxResults,proto3" json:"max_results,omitempty"`
	Method     Method                 `protobuf:"varint,4,opt,name=method,proto3,enum=geocoder.Method" json:"method,omitempty"`
}

func (x *GeocodeRequest) Reset() {
	*x = GeocodeRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_geocoder_proto_msgTypes[5]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GeocodeRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GeocodeRequest) ProtoMessage() {}

func (x *GeocodeRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_geocoder_proto_msgTypes[5]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GeocodeRequest.ProtoReflect.Descriptor instead.
func (*GeocodeRequest) Descriptor() ([]byte, []int) {
	return file_proto_geocoder_proto_rawDescGZIP(), []int{5}
}

func (m *GeocodeRequest) GetQuery() isGeocodeRequest_Query {
	if m != nil {
		return m.Query
	}
	return nil
}

func (x *GeocodeRequest) GetAddressQuery() string {
	if x, ok := x.GetQuery().(*GeocodeRequest_AddressQuery); ok {
		return x.AddressQuery
	}
	return ""
}

func (x *GeocodeRequest) GetPointQuery() *Point {
	if x, ok := x.GetQuery().(*GeocodeRequest_PointQuery); ok {
		return x.PointQuery
	}
	return nil
}

func (x *GeocodeRequest) GetMaxResults() uint32 {
	if x != nil {
		return x.MaxResults
	}
	return 0
}

func (x *GeocodeRequest) GetMethod() Method {
	if x != nil {
		return x.Method
	}
	return Method_FWD_FUZZY
}

type isGeocodeRequest_Query interface {
	isGeocodeRequest_Query()
}

type GeocodeRequest_AddressQuery struct {
	AddressQuery string `protobuf:"bytes,1,opt,name=address_query,json=addressQuery,proto3,oneof"` //
}

type GeocodeRequest_PointQuery struct {
	PointQuery *Point `protobuf:"bytes,2,opt,name=point_query,json=pointQuery,proto3,oneof"` //
}

func (*GeocodeRequest_AddressQuery) isGeocodeRequest_Query() {}

func (*GeocodeRequest_PointQuery) isGeocodeRequest_Query() {}

// GeocodeResponse
type GeocodeResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Result     []*ScoredAddress `protobuf:"bytes,1,rep,name=result,proto3" json:"result,omitempty"`
	NumResults uint32           `protobuf:"varint,2,opt,name=num_results,json=numResults,proto3" json:"num_results,omitempty"`
}

func (x *GeocodeResponse) Reset() {
	*x = GeocodeResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_geocoder_proto_msgTypes[6]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GeocodeResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GeocodeResponse) ProtoMessage() {}

func (x *GeocodeResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_geocoder_proto_msgTypes[6]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GeocodeResponse.ProtoReflect.Descriptor instead.
func (*GeocodeResponse) Descriptor() ([]byte, []int) {
	return file_proto_geocoder_proto_rawDescGZIP(), []int{6}
}

func (x *GeocodeResponse) GetResult() []*ScoredAddress {
	if x != nil {
		return x.Result
	}
	return nil
}

func (x *GeocodeResponse) GetNumResults() uint32 {
	if x != nil {
		return x.NumResults
	}
	return 0
}

var File_proto_geocoder_proto protoreflect.FileDescriptor

var file_proto_geocoder_proto_rawDesc = []byte{
	0x0a, 0x14, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2f, 0x67, 0x65, 0x6f, 0x63, 0x6f, 0x64, 0x65, 0x72,
	0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x08, 0x67, 0x65, 0x6f, 0x63, 0x6f, 0x64, 0x65, 0x72,
	0x22, 0x41, 0x0a, 0x05, 0x50, 0x6f, 0x69, 0x6e, 0x74, 0x12, 0x1a, 0x0a, 0x08, 0x6c, 0x61, 0x74,
	0x69, 0x74, 0x75, 0x64, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x02, 0x52, 0x08, 0x6c, 0x61, 0x74,
	0x69, 0x74, 0x75, 0x64, 0x65, 0x12, 0x1c, 0x0a, 0x09, 0x6c, 0x6f, 0x6e, 0x67, 0x69, 0x74, 0x75,
	0x64, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x02, 0x52, 0x09, 0x6c, 0x6f, 0x6e, 0x67, 0x69, 0x74,
	0x75, 0x64, 0x65, 0x22, 0x9a, 0x01, 0x0a, 0x0b, 0x41, 0x64, 0x64, 0x72, 0x65, 0x73, 0x73, 0x44,
	0x61, 0x74, 0x61, 0x12, 0x1b, 0x0a, 0x09, 0x68, 0x6f, 0x75, 0x73, 0x65, 0x5f, 0x6e, 0x75, 0x6d,
	0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x08, 0x68, 0x6f, 0x75, 0x73, 0x65, 0x4e, 0x75, 0x6d,
	0x12, 0x28, 0x0a, 0x10, 0x66, 0x75, 0x6c, 0x6c, 0x5f, 0x73, 0x74, 0x72, 0x65, 0x65, 0x74, 0x5f,
	0x6e, 0x61, 0x6d, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0e, 0x66, 0x75, 0x6c, 0x6c,
	0x53, 0x74, 0x72, 0x65, 0x65, 0x74, 0x4e, 0x61, 0x6d, 0x65, 0x12, 0x2a, 0x0a, 0x08, 0x62, 0x6f,
	0x72, 0x6f, 0x63, 0x6f, 0x64, 0x65, 0x18, 0x03, 0x20, 0x01, 0x28, 0x0e, 0x32, 0x0e, 0x2e, 0x67,
	0x65, 0x6f, 0x63, 0x6f, 0x64, 0x65, 0x72, 0x2e, 0x42, 0x6f, 0x72, 0x6f, 0x52, 0x08, 0x62, 0x6f,
	0x72, 0x6f, 0x63, 0x6f, 0x64, 0x65, 0x12, 0x18, 0x0a, 0x07, 0x7a, 0x69, 0x70, 0x63, 0x6f, 0x64,
	0x65, 0x18, 0x04, 0x20, 0x01, 0x28, 0x09, 0x52, 0x07, 0x7a, 0x69, 0x70, 0x63, 0x6f, 0x64, 0x65,
	0x22, 0x71, 0x0a, 0x07, 0x41, 0x64, 0x64, 0x72, 0x65, 0x73, 0x73, 0x12, 0x2b, 0x0a, 0x08, 0x6c,
	0x6f, 0x63, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x0f, 0x2e,
	0x67, 0x65, 0x6f, 0x63, 0x6f, 0x64, 0x65, 0x72, 0x2e, 0x50, 0x6f, 0x69, 0x6e, 0x74, 0x52, 0x08,
	0x6c, 0x6f, 0x63, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x12, 0x29, 0x0a, 0x04, 0x64, 0x61, 0x74, 0x61,
	0x18, 0x02, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x15, 0x2e, 0x67, 0x65, 0x6f, 0x63, 0x6f, 0x64, 0x65,
	0x72, 0x2e, 0x41, 0x64, 0x64, 0x72, 0x65, 0x73, 0x73, 0x44, 0x61, 0x74, 0x61, 0x52, 0x04, 0x64,
	0x61, 0x74, 0x61, 0x12, 0x0e, 0x0a, 0x02, 0x69, 0x64, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52,
	0x02, 0x69, 0x64, 0x22, 0x5a, 0x0a, 0x0a, 0x49, 0x4f, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73,
	0x65, 0x12, 0x18, 0x0a, 0x07, 0x73, 0x75, 0x63, 0x63, 0x65, 0x73, 0x73, 0x18, 0x01, 0x20, 0x01,
	0x28, 0x08, 0x52, 0x07, 0x73, 0x75, 0x63, 0x63, 0x65, 0x73, 0x73, 0x12, 0x32, 0x0a, 0x15, 0x74,
	0x6f, 0x74, 0x61, 0x6c, 0x5f, 0x6f, 0x62, 0x6a, 0x65, 0x63, 0x74, 0x73, 0x5f, 0x77, 0x72, 0x69,
	0x74, 0x74, 0x65, 0x6e, 0x18, 0x02, 0x20, 0x01, 0x28, 0x05, 0x52, 0x13, 0x74, 0x6f, 0x74, 0x61,
	0x6c, 0x4f, 0x62, 0x6a, 0x65, 0x63, 0x74, 0x73, 0x57, 0x72, 0x69, 0x74, 0x74, 0x65, 0x6e, 0x22,
	0x99, 0x01, 0x0a, 0x0d, 0x53, 0x63, 0x6f, 0x72, 0x65, 0x64, 0x41, 0x64, 0x64, 0x72, 0x65, 0x73,
	0x73, 0x12, 0x2b, 0x0a, 0x07, 0x61, 0x64, 0x64, 0x72, 0x65, 0x73, 0x73, 0x18, 0x01, 0x20, 0x01,
	0x28, 0x0b, 0x32, 0x11, 0x2e, 0x67, 0x65, 0x6f, 0x63, 0x6f, 0x64, 0x65, 0x72, 0x2e, 0x41, 0x64,
	0x64, 0x72, 0x65, 0x73, 0x73, 0x52, 0x07, 0x61, 0x64, 0x64, 0x72, 0x65, 0x73, 0x73, 0x12, 0x2b,
	0x0a, 0x11, 0x6e, 0x6f, 0x72, 0x6d, 0x65, 0x64, 0x5f, 0x63, 0x6f, 0x6e, 0x66, 0x69, 0x64, 0x65,
	0x6e, 0x63, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x02, 0x52, 0x10, 0x6e, 0x6f, 0x72, 0x6d, 0x65,
	0x64, 0x43, 0x6f, 0x6e, 0x66, 0x69, 0x64, 0x65, 0x6e, 0x63, 0x65, 0x12, 0x2e, 0x0a, 0x13, 0x66,
	0x75, 0x6c, 0x6c, 0x5f, 0x73, 0x74, 0x72, 0x65, 0x65, 0x74, 0x5f, 0x61, 0x64, 0x64, 0x72, 0x65,
	0x73, 0x73, 0x18, 0x04, 0x20, 0x01, 0x28, 0x09, 0x52, 0x11, 0x66, 0x75, 0x6c, 0x6c, 0x53, 0x74,
	0x72, 0x65, 0x65, 0x74, 0x41, 0x64, 0x64, 0x72, 0x65, 0x73, 0x73, 0x22, 0xbf, 0x01, 0x0a, 0x0e,
	0x47, 0x65, 0x6f, 0x63, 0x6f, 0x64, 0x65, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x25,
	0x0a, 0x0d, 0x61, 0x64, 0x64, 0x72, 0x65, 0x73, 0x73, 0x5f, 0x71, 0x75, 0x65, 0x72, 0x79, 0x18,
	0x01, 0x20, 0x01, 0x28, 0x09, 0x48, 0x00, 0x52, 0x0c, 0x61, 0x64, 0x64, 0x72, 0x65, 0x73, 0x73,
	0x51, 0x75, 0x65, 0x72, 0x79, 0x12, 0x32, 0x0a, 0x0b, 0x70, 0x6f, 0x69, 0x6e, 0x74, 0x5f, 0x71,
	0x75, 0x65, 0x72, 0x79, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x0f, 0x2e, 0x67, 0x65, 0x6f,
	0x63, 0x6f, 0x64, 0x65, 0x72, 0x2e, 0x50, 0x6f, 0x69, 0x6e, 0x74, 0x48, 0x00, 0x52, 0x0a, 0x70,
	0x6f, 0x69, 0x6e, 0x74, 0x51, 0x75, 0x65, 0x72, 0x79, 0x12, 0x1f, 0x0a, 0x0b, 0x6d, 0x61, 0x78,
	0x5f, 0x72, 0x65, 0x73, 0x75, 0x6c, 0x74, 0x73, 0x18, 0x03, 0x20, 0x01, 0x28, 0x0d, 0x52, 0x0a,
	0x6d, 0x61, 0x78, 0x52, 0x65, 0x73, 0x75, 0x6c, 0x74, 0x73, 0x12, 0x28, 0x0a, 0x06, 0x6d, 0x65,
	0x74, 0x68, 0x6f, 0x64, 0x18, 0x04, 0x20, 0x01, 0x28, 0x0e, 0x32, 0x10, 0x2e, 0x67, 0x65, 0x6f,
	0x63, 0x6f, 0x64, 0x65, 0x72, 0x2e, 0x4d, 0x65, 0x74, 0x68, 0x6f, 0x64, 0x52, 0x06, 0x6d, 0x65,
	0x74, 0x68, 0x6f, 0x64, 0x42, 0x07, 0x0a, 0x05, 0x71, 0x75, 0x65, 0x72, 0x79, 0x22, 0x63, 0x0a,
	0x0f, 0x47, 0x65, 0x6f, 0x63, 0x6f, 0x64, 0x65, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65,
	0x12, 0x2f, 0x0a, 0x06, 0x72, 0x65, 0x73, 0x75, 0x6c, 0x74, 0x18, 0x01, 0x20, 0x03, 0x28, 0x0b,
	0x32, 0x17, 0x2e, 0x67, 0x65, 0x6f, 0x63, 0x6f, 0x64, 0x65, 0x72, 0x2e, 0x53, 0x63, 0x6f, 0x72,
	0x65, 0x64, 0x41, 0x64, 0x64, 0x72, 0x65, 0x73, 0x73, 0x52, 0x06, 0x72, 0x65, 0x73, 0x75, 0x6c,
	0x74, 0x12, 0x1f, 0x0a, 0x0b, 0x6e, 0x75, 0x6d, 0x5f, 0x72, 0x65, 0x73, 0x75, 0x6c, 0x74, 0x73,
	0x18, 0x02, 0x20, 0x01, 0x28, 0x0d, 0x52, 0x0a, 0x6e, 0x75, 0x6d, 0x52, 0x65, 0x73, 0x75, 0x6c,
	0x74, 0x73, 0x2a, 0x89, 0x01, 0x0a, 0x04, 0x42, 0x6f, 0x72, 0x6f, 0x12, 0x0d, 0x0a, 0x09, 0x55,
	0x4e, 0x44, 0x45, 0x46, 0x49, 0x4e, 0x45, 0x44, 0x10, 0x00, 0x12, 0x0d, 0x0a, 0x09, 0x4d, 0x41,
	0x4e, 0x48, 0x41, 0x54, 0x54, 0x41, 0x4e, 0x10, 0x01, 0x12, 0x09, 0x0a, 0x05, 0x42, 0x52, 0x4f,
	0x4e, 0x58, 0x10, 0x02, 0x12, 0x0c, 0x0a, 0x08, 0x42, 0x52, 0x4f, 0x4f, 0x4b, 0x4c, 0x59, 0x4e,
	0x10, 0x03, 0x12, 0x0a, 0x0a, 0x06, 0x51, 0x55, 0x45, 0x45, 0x4e, 0x53, 0x10, 0x04, 0x12, 0x11,
	0x0a, 0x0d, 0x53, 0x54, 0x41, 0x54, 0x45, 0x4e, 0x5f, 0x49, 0x53, 0x4c, 0x41, 0x4e, 0x44, 0x10,
	0x05, 0x12, 0x0a, 0x0a, 0x06, 0x4e, 0x41, 0x53, 0x53, 0x41, 0x55, 0x10, 0x06, 0x12, 0x0f, 0x0a,
	0x0b, 0x57, 0x45, 0x53, 0x54, 0x43, 0x48, 0x45, 0x53, 0x54, 0x45, 0x52, 0x10, 0x07, 0x12, 0x0e,
	0x0a, 0x0a, 0x4e, 0x45, 0x57, 0x5f, 0x4a, 0x45, 0x52, 0x53, 0x45, 0x59, 0x10, 0x08, 0x2a, 0x28,
	0x0a, 0x06, 0x4d, 0x65, 0x74, 0x68, 0x6f, 0x64, 0x12, 0x0d, 0x0a, 0x09, 0x46, 0x57, 0x44, 0x5f,
	0x46, 0x55, 0x5a, 0x5a, 0x59, 0x10, 0x00, 0x12, 0x0f, 0x0a, 0x0b, 0x52, 0x45, 0x56, 0x5f, 0x4e,
	0x45, 0x41, 0x52, 0x45, 0x53, 0x54, 0x10, 0x01, 0x32, 0x97, 0x01, 0x0a, 0x08, 0x47, 0x65, 0x6f,
	0x63, 0x6f, 0x64, 0x65, 0x72, 0x12, 0x49, 0x0a, 0x1a, 0x49, 0x6e, 0x73, 0x65, 0x72, 0x74, 0x6f,
	0x72, 0x52, 0x65, 0x70, 0x6c, 0x61, 0x63, 0x65, 0x41, 0x64, 0x64, 0x72, 0x65, 0x73, 0x73, 0x44,
	0x61, 0x74, 0x61, 0x12, 0x11, 0x2e, 0x67, 0x65, 0x6f, 0x63, 0x6f, 0x64, 0x65, 0x72, 0x2e, 0x41,
	0x64, 0x64, 0x72, 0x65, 0x73, 0x73, 0x1a, 0x14, 0x2e, 0x67, 0x65, 0x6f, 0x63, 0x6f, 0x64, 0x65,
	0x72, 0x2e, 0x49, 0x4f, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x22, 0x00, 0x28, 0x01,
	0x12, 0x40, 0x0a, 0x07, 0x47, 0x65, 0x6f, 0x63, 0x6f, 0x64, 0x65, 0x12, 0x18, 0x2e, 0x67, 0x65,
	0x6f, 0x63, 0x6f, 0x64, 0x65, 0x72, 0x2e, 0x47, 0x65, 0x6f, 0x63, 0x6f, 0x64, 0x65, 0x52, 0x65,
	0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x19, 0x2e, 0x67, 0x65, 0x6f, 0x63, 0x6f, 0x64, 0x65, 0x72,
	0x2e, 0x47, 0x65, 0x6f, 0x63, 0x6f, 0x64, 0x65, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65,
	0x22, 0x00, 0x42, 0x1f, 0x5a, 0x1d, 0x67, 0x65, 0x6f, 0x63, 0x6f, 0x64, 0x65, 0x72, 0x2f, 0x70,
	0x72, 0x6f, 0x74, 0x6f, 0x2f, 0x67, 0x65, 0x6f, 0x63, 0x6f, 0x64, 0x65, 0x72, 0x2e, 0x70, 0x72,
	0x6f, 0x74, 0x6f, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_proto_geocoder_proto_rawDescOnce sync.Once
	file_proto_geocoder_proto_rawDescData = file_proto_geocoder_proto_rawDesc
)

func file_proto_geocoder_proto_rawDescGZIP() []byte {
	file_proto_geocoder_proto_rawDescOnce.Do(func() {
		file_proto_geocoder_proto_rawDescData = protoimpl.X.CompressGZIP(file_proto_geocoder_proto_rawDescData)
	})
	return file_proto_geocoder_proto_rawDescData
}

var file_proto_geocoder_proto_enumTypes = make([]protoimpl.EnumInfo, 2)
var file_proto_geocoder_proto_msgTypes = make([]protoimpl.MessageInfo, 7)
var file_proto_geocoder_proto_goTypes = []interface{}{
	(Boro)(0),               // 0: geocoder.Boro
	(Method)(0),             // 1: geocoder.Method
	(*Point)(nil),           // 2: geocoder.Point
	(*AddressData)(nil),     // 3: geocoder.AddressData
	(*Address)(nil),         // 4: geocoder.Address
	(*IOResponse)(nil),      // 5: geocoder.IOResponse
	(*ScoredAddress)(nil),   // 6: geocoder.ScoredAddress
	(*GeocodeRequest)(nil),  // 7: geocoder.GeocodeRequest
	(*GeocodeResponse)(nil), // 8: geocoder.GeocodeResponse
}
var file_proto_geocoder_proto_depIdxs = []int32{
	0, // 0: geocoder.AddressData.borocode:type_name -> geocoder.Boro
	2, // 1: geocoder.Address.location:type_name -> geocoder.Point
	3, // 2: geocoder.Address.data:type_name -> geocoder.AddressData
	4, // 3: geocoder.ScoredAddress.address:type_name -> geocoder.Address
	2, // 4: geocoder.GeocodeRequest.point_query:type_name -> geocoder.Point
	1, // 5: geocoder.GeocodeRequest.method:type_name -> geocoder.Method
	6, // 6: geocoder.GeocodeResponse.result:type_name -> geocoder.ScoredAddress
	4, // 7: geocoder.Geocoder.InsertorReplaceAddressData:input_type -> geocoder.Address
	7, // 8: geocoder.Geocoder.Geocode:input_type -> geocoder.GeocodeRequest
	5, // 9: geocoder.Geocoder.InsertorReplaceAddressData:output_type -> geocoder.IOResponse
	8, // 10: geocoder.Geocoder.Geocode:output_type -> geocoder.GeocodeResponse
	9, // [9:11] is the sub-list for method output_type
	7, // [7:9] is the sub-list for method input_type
	7, // [7:7] is the sub-list for extension type_name
	7, // [7:7] is the sub-list for extension extendee
	0, // [0:7] is the sub-list for field type_name
}

func init() { file_proto_geocoder_proto_init() }
func file_proto_geocoder_proto_init() {
	if File_proto_geocoder_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_proto_geocoder_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Point); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_geocoder_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*AddressData); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_geocoder_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Address); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_geocoder_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*IOResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_geocoder_proto_msgTypes[4].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ScoredAddress); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_geocoder_proto_msgTypes[5].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GeocodeRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_geocoder_proto_msgTypes[6].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GeocodeResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	file_proto_geocoder_proto_msgTypes[5].OneofWrappers = []interface{}{
		(*GeocodeRequest_AddressQuery)(nil),
		(*GeocodeRequest_PointQuery)(nil),
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_proto_geocoder_proto_rawDesc,
			NumEnums:      2,
			NumMessages:   7,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_proto_geocoder_proto_goTypes,
		DependencyIndexes: file_proto_geocoder_proto_depIdxs,
		EnumInfos:         file_proto_geocoder_proto_enumTypes,
		MessageInfos:      file_proto_geocoder_proto_msgTypes,
	}.Build()
	File_proto_geocoder_proto = out.File
	file_proto_geocoder_proto_rawDesc = nil
	file_proto_geocoder_proto_goTypes = nil
	file_proto_geocoder_proto_depIdxs = nil
}
